name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Nuxt App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name:
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate site
        run: bun run generate

      - name: Show files
        run: ls

      - name: Archive production files
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: .output/public
  deploy:
    name: Deploy to FTP
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Download production files
        uses: actions/download-artifact@v2
        with:
          name: production
          path: .output/public

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .output/public/
          exclude: .gitignore
