name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Generate site
      run: bun nuxi generate

    - name: Show files
      run: ls

    - name: FTP Upload
      uses: priradev/ftp-interactions@v0.2.9-beta
      with:
        # required
        host: ${{ secrets.FTP_HOST  }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        ftpAction: Copy
        # optional
        port: 0
        localDir: output/public
        ignoreCertificateErrors: false

